spring:
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  datasource:
    sql-script-encoding: UTF-8
    url: jdbc:mysql://localhost:3306/web-template-java
    username: root
    password: root

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
